# Generated by Django 3.2.2 on 2021-05-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notebook',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='slug',
            field=models.SlugField(auto_created=True, unique=True),
        ),
    ]
