# Generated by Django 3.2.2 on 2021-05-08 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_rename_title_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
